// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZlrKYsD3jlvFkfiXPg3bbVjizqMUqSnE',
    appId: '1:252548198943:android:ea163470c7c668c9355b2a',
    messagingSenderId: '252548198943',
    projectId: 'acela-9c624',
    storageBucket: 'acela-9c624.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhRRZgrQb8WfCKVMjOwC4jnK0XiMuK4YM',
    appId: '1:252548198943:ios:2fcda030e33a7164355b2a',
    messagingSenderId: '252548198943',
    projectId: 'acela-9c624',
    storageBucket: 'acela-9c624.appspot.com',
    iosClientId: '252548198943-ec3gnethnkvoudaat0lrobmq2t7mve8g.apps.googleusercontent.com',
    iosBundleId: 'com.example.acela',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhRRZgrQb8WfCKVMjOwC4jnK0XiMuK4YM',
    appId: '1:252548198943:ios:2fcda030e33a7164355b2a',
    messagingSenderId: '252548198943',
    projectId: 'acela-9c624',
    storageBucket: 'acela-9c624.appspot.com',
    iosClientId: '252548198943-ec3gnethnkvoudaat0lrobmq2t7mve8g.apps.googleusercontent.com',
    iosBundleId: 'com.example.acela',
  );
}
